from __future__ import annotations

from datetime import datetime
from zoneinfo import ZoneInfo

from mailmap.model import Intencion, Rubro, SyntheticMessage

CORDOBA = ZoneInfo("America/Argentina/Cordoba")


def _at(value: str) -> datetime:
    return datetime.fromisoformat(value).replace(tzinfo=CORDOBA)


def synthetic_messages() -> tuple[SyntheticMessage, ...]:
    """Dataset determinista. Todos los nombres y dominios son ficticios."""

    return (
        SyntheticMessage(
            id="nube-security-01",
            thread_id="nube-security-thread",
            received_at=_at("2026-08-15T22:40:00"),
            sender_name="Nube Clara Seguridad",
            sender_email="seguridad@nube-clara.example",
            subject="Nuevo inicio de sesión detectado",
            labels=("INBOX", "CATEGORY_PROMOTIONS", "IMPORTANT"),
            gmail_category="Promociones",
            authenticated_domain="nube-clara.example",
            list_id=None,
            unsubscribe_method=None,
            dkim_pass=True,
            dmarc_pass=True,
            brand_hint="Nube Clara",
            rubro_hint=Rubro.SOFTWARE,
            flow_hint=Intencion.SEGURIDAD,
            size_bytes=18240,
            fixture_tags=("same-source-multiple-flows", "security-miscategorized", "important"),
        ),
        SyntheticMessage(
            id="nube-invoice-01",
            thread_id="nube-invoice-thread",
            received_at=_at("2026-08-08T09:12:00"),
            sender_name="Nube Clara",
            sender_email="facturacion@nube-clara.example",
            subject="Factura NC-1048 de agosto",
            labels=("INBOX", "CATEGORY_PROMOTIONS", "Pagos"),
            gmail_category="Promociones",
            authenticated_domain="nube-clara.example",
            list_id="clientes.nube-clara.example",
            unsubscribe_method="manual",
            dkim_pass=True,
            dmarc_pass=True,
            brand_hint="Nube Clara",
            rubro_hint=Rubro.SOFTWARE,
            flow_hint=Intencion.DOCUMENTO,
            size_bytes=46380,
            fixture_tags=("same-source-multiple-flows", "invoice-inside-promo", "custom-label"),
        ),
        SyntheticMessage(
            id="nube-promo-01",
            thread_id="nube-promo-thread-01",
            received_at=_at("2026-07-26T12:05:00"),
            sender_name="Nube Clara Novedades",
            sender_email="boletines@nube-clara.example",
            subject="Duplicá el espacio de tu equipo por seis meses",
            labels=("INBOX", "CATEGORY_PROMOTIONS"),
            gmail_category="Promociones",
            authenticated_domain="nube-clara.example",
            list_id="novedades.nube-clara.example",
            unsubscribe_method="one_click",
            dkim_pass=True,
            dmarc_pass=True,
            brand_hint="Nube Clara",
            rubro_hint=Rubro.SOFTWARE,
            flow_hint=Intencion.PROMOCIONAL,
            size_bytes=89210,
            fixture_tags=("same-source-multiple-flows",),
        ),
        SyntheticMessage(
            id="nube-promo-old-domain",
            thread_id="nube-promo-thread-old",
            received_at=_at("2025-11-18T10:15:00"),
            sender_name="Nube Clara",
            sender_email="avisos@nubeclara.example",
            subject="Tu resumen mensual de almacenamiento",
            labels=("INBOX", "CATEGORY_UPDATES"),
            gmail_category="Actualizaciones",
            authenticated_domain="nubeclara.example",
            list_id="clientes.nube-clara.example",
            unsubscribe_method="one_click",
            dkim_pass=True,
            dmarc_pass=True,
            brand_hint="Nube Clara",
            rubro_hint=Rubro.SOFTWARE,
            flow_hint=Intencion.NOTIFICACION,
            size_bytes=35120,
            fixture_tags=("brand-domain-change",),
        ),
        SyntheticMessage(
            id="cocina-news-01",
            thread_id="cocina-news-thread",
            received_at=_at("2026-08-12T18:00:00"),
            sender_name="Cocina Norte",
            sender_email="cocina-norte@envios.fabricamail.example",
            subject="Cinco platos simples para una noche fría",
            labels=("INBOX", "CATEGORY_UPDATES"),
            gmail_category="Actualizaciones",
            authenticated_domain="cocinanorte.example",
            list_id="lectores.cocinanorte.example",
            unsubscribe_method="one_click",
            dkim_pass=True,
            dmarc_pass=True,
            brand_hint="Cocina Norte",
            rubro_hint=Rubro.MEDIOS,
            flow_hint=Intencion.EDITORIAL,
            size_bytes=104500,
            fixture_tags=("different-brands-same-esp",),
        ),
        SyntheticMessage(
            id="ruta-news-01",
            thread_id="ruta-news-thread",
            received_at=_at("2026-08-12T18:05:00"),
            sender_name="Ruta Viva",
            sender_email="ruta-viva@envios.fabricamail.example",
            subject="Escapadas breves para descubrir las sierras",
            labels=("INBOX", "CATEGORY_UPDATES"),
            gmail_category="Actualizaciones",
            authenticated_domain="rutaviva.example",
            list_id="viajeros.rutaviva.example",
            unsubscribe_method="one_click",
            dkim_pass=True,
            dmarc_pass=True,
            brand_hint="Ruta Viva",
            rubro_hint=Rubro.VIAJES,
            flow_hint=Intencion.EDITORIAL,
            size_bytes=98340,
            fixture_tags=("different-brands-same-esp",),
        ),
        SyntheticMessage(
            id="horizonte-news-01",
            thread_id="horizonte-news-thread-01",
            received_at=_at("2026-08-16T07:30:00"),
            sender_name="Diario Horizonte",
            sender_email="edicion@diariohorizonte.example",
            subject="Las siete noticias para empezar el domingo",
            labels=("INBOX", "CATEGORY_UPDATES", "UNREAD"),
            gmail_category="Actualizaciones",
            authenticated_domain="diariohorizonte.example",
            list_id="manana.diariohorizonte.example",
            unsubscribe_method="one_click",
            dkim_pass=True,
            dmarc_pass=True,
            brand_hint="Diario Horizonte",
            rubro_hint=Rubro.MEDIOS,
            flow_hint=Intencion.EDITORIAL,
            size_bytes=132440,
            fixture_tags=("one-click-newsletter",),
        ),
        SyntheticMessage(
            id="horizonte-news-02",
            thread_id="horizonte-news-thread-02",
            received_at=_at("2026-08-15T07:30:00"),
            sender_name="Diario Horizonte",
            sender_email="edicion@diariohorizonte.example",
            subject="El mapa de temas que dejó la semana",
            labels=("INBOX", "CATEGORY_UPDATES"),
            gmail_category="Actualizaciones",
            authenticated_domain="diariohorizonte.example",
            list_id="manana.diariohorizonte.example",
            unsubscribe_method="one_click",
            dkim_pass=True,
            dmarc_pass=True,
            brand_hint="Diario Horizonte",
            rubro_hint=Rubro.MEDIOS,
            flow_hint=Intencion.EDITORIAL,
            size_bytes=127800,
            fixture_tags=("one-click-newsletter",),
        ),
        SyntheticMessage(
            id="bitacora-news-01",
            thread_id="bitacora-news-thread",
            received_at=_at("2026-08-11T20:20:00"),
            sender_name="Bitácora Técnica",
            sender_email="hola@bitacoratecnica.example",
            subject="Edición 42: software pequeño que dura años",
            labels=("INBOX", "CATEGORY_UPDATES"),
            gmail_category="Actualizaciones",
            authenticated_domain="bitacoratecnica.example",
            list_id="semanal.bitacoratecnica.example",
            unsubscribe_method="manual",
            dkim_pass=True,
            dmarc_pass=True,
            brand_hint="Bitácora Técnica",
            rubro_hint=Rubro.MEDIOS,
            flow_hint=Intencion.EDITORIAL,
            size_bytes=75400,
            fixture_tags=("manual-newsletter",),
        ),
        SyntheticMessage(
            id="faro-spoof-01",
            thread_id="faro-spoof-thread",
            received_at=_at("2026-08-16T03:14:00"),
            sender_name="Banco Faro",
            sender_email="verificacion@banco-faro-seguro.invalid.example",
            subject="URGENTE: validá tu cuenta ahora",
            labels=("SPAM", "UNREAD"),
            gmail_category="Spam",
            authenticated_domain=None,
            list_id=None,
            unsubscribe_method="unsafe",
            dkim_pass=False,
            dmarc_pass=False,
            brand_hint="Banco Faro",
            rubro_hint=Rubro.FINANZAS,
            flow_hint=Intencion.SOSPECHOSO,
            size_bytes=22990,
            fixture_tags=("brand-spoof-spam",),
        ),
        SyntheticMessage(
            id="nora-personal-01",
            thread_id="nora-personal-thread",
            received_at=_at("2026-08-14T17:45:00"),
            sender_name="Taller de Nora",
            sender_email="nora@taller-nora.example",
            subject="Te guardé el cuaderno azul que me pediste",
            labels=("INBOX", "CATEGORY_UPDATES"),
            gmail_category="Actualizaciones",
            authenticated_domain="taller-nora.example",
            list_id="avisos.taller-nora.example",
            unsubscribe_method="manual",
            dkim_pass=True,
            dmarc_pass=True,
            brand_hint="Taller de Nora",
            rubro_hint=Rubro.PERSONAL,
            flow_hint=Intencion.PERSONAL,
            personal_signal=True,
            size_bytes=12480,
            fixture_tags=("personal-misclassified-automated",),
        ),
        SyntheticMessage(
            id="orbit-thread-01",
            thread_id="orbit-mixed-thread",
            received_at=_at("2026-08-01T11:00:00"),
            sender_name="Proyecto Órbita",
            sender_email="equipo@proyecto-orbita.example",
            subject="Re: cronograma del taller",
            labels=("INBOX", "STARRED", "Trabajo"),
            gmail_category="Principal",
            authenticated_domain="proyecto-orbita.example",
            list_id=None,
            unsubscribe_method=None,
            dkim_pass=True,
            dmarc_pass=True,
            brand_hint="Proyecto Órbita",
            rubro_hint=Rubro.TRABAJO,
            flow_hint=Intencion.OPERATIVO,
            size_bytes=19500,
            fixture_tags=("mixed-protection-thread", "starred", "custom-label"),
        ),
        SyntheticMessage(
            id="orbit-thread-02",
            thread_id="orbit-mixed-thread",
            received_at=_at("2026-08-01T11:22:00"),
            sender_name="Proyecto Órbita",
            sender_email="equipo@proyecto-orbita.example",
            subject="Re: cronograma del taller",
            labels=("INBOX",),
            gmail_category="Principal",
            authenticated_domain="proyecto-orbita.example",
            list_id=None,
            unsubscribe_method=None,
            dkim_pass=True,
            dmarc_pass=True,
            brand_hint="Proyecto Órbita",
            rubro_hint=Rubro.TRABAJO,
            flow_hint=Intencion.OPERATIVO,
            size_bytes=16200,
            fixture_tags=("mixed-protection-thread",),
        ),
        SyntheticMessage(
            id="cordoba-boundary-before",
            thread_id="ciudad-clara-01",
            received_at=_at("2026-07-31T23:59:30"),
            sender_name="Ciudad Clara",
            sender_email="novedades@ciudadclara.example",
            subject="Agenda ciudadana del viernes",
            labels=("INBOX", "CATEGORY_UPDATES"),
            gmail_category="Actualizaciones",
            authenticated_domain="ciudadclara.example",
            list_id="agenda.ciudadclara.example",
            unsubscribe_method="one_click",
            dkim_pass=True,
            dmarc_pass=True,
            brand_hint="Ciudad Clara",
            rubro_hint=Rubro.SALUD,
            flow_hint=Intencion.NOTIFICACION,
            size_bytes=56120,
            fixture_tags=("cordoba-civil-boundary",),
        ),
        SyntheticMessage(
            id="cordoba-boundary-after",
            thread_id="ciudad-clara-02",
            received_at=_at("2026-08-01T00:00:30"),
            sender_name="Ciudad Clara",
            sender_email="novedades@ciudadclara.example",
            subject="Agenda ciudadana del sábado",
            labels=("INBOX", "CATEGORY_UPDATES"),
            gmail_category="Actualizaciones",
            authenticated_domain="ciudadclara.example",
            list_id="agenda.ciudadclara.example",
            unsubscribe_method="one_click",
            dkim_pass=True,
            dmarc_pass=True,
            brand_hint="Ciudad Clara",
            rubro_hint=Rubro.SALUD,
            flow_hint=Intencion.NOTIFICACION,
            size_bytes=57310,
            fixture_tags=("cordoba-civil-boundary",),
        ),
        SyntheticMessage(
            id="sync-retry-01",
            thread_id="estado-sync-01",
            received_at=_at("2026-08-10T14:10:00"),
            sender_name="Estado Sync",
            sender_email="estado@sync-laboratorio.example",
            subject="Resumen procesado después del segundo intento",
            labels=("INBOX", "CATEGORY_UPDATES"),
            gmail_category="Actualizaciones",
            authenticated_domain="sync-laboratorio.example",
            list_id="estado.sync-laboratorio.example",
            unsubscribe_method="manual",
            dkim_pass=True,
            dmarc_pass=True,
            brand_hint="Estado Sync",
            rubro_hint=Rubro.SOFTWARE,
            flow_hint=Intencion.OPERATIVO,
            size_bytes=32100,
            failure_state="recovered_after_retry",
            fixture_tags=("partial-failure-retry",),
        ),
        SyntheticMessage(
            id="sync-partial-02",
            thread_id="estado-sync-02",
            received_at=_at("2026-08-09T14:10:00"),
            sender_name="Estado Sync",
            sender_email="estado@sync-laboratorio.example",
            subject="Registro con metadatos parciales",
            labels=("INBOX", "CATEGORY_UPDATES"),
            gmail_category="Actualizaciones",
            authenticated_domain="sync-laboratorio.example",
            list_id=None,
            unsubscribe_method=None,
            dkim_pass=True,
            dmarc_pass=True,
            brand_hint="Estado Sync",
            rubro_hint=Rubro.SOFTWARE,
            flow_hint=Intencion.OPERATIVO,
            size_bytes=0,
            failure_state="partial_metadata",
            fixture_tags=("partial-failure-retry",),
        ),
        SyntheticMessage(
            id="obsolete-plan-01",
            thread_id="ofertas-limon-01",
            received_at=_at("2025-10-02T16:30:00"),
            sender_name="Mercado Limón",
            sender_email="ofertas@mercadolimon.example",
            subject="Último día de descuentos de temporada",
            labels=("INBOX", "CATEGORY_PROMOTIONS"),
            gmail_category="Promociones",
            authenticated_domain="mercadolimon.example",
            list_id="ofertas.mercadolimon.example",
            unsubscribe_method="one_click",
            dkim_pass=True,
            dmarc_pass=True,
            brand_hint="Mercado Limón",
            rubro_hint=Rubro.COMERCIO,
            flow_hint=Intencion.PROMOCIONAL,
            size_bytes=111900,
            fixture_tags=("obsolete-plan-label-change",),
        ),
        SyntheticMessage(
            id="ambiguous-sender-a",
            thread_id="ambiguous-a",
            received_at=_at("2026-06-04T10:00:00"),
            sender_name="Novedades",
            sender_email="grupo-a@dispatch-compartido.example",
            subject="Tu selección semanal",
            labels=("INBOX", "CATEGORY_PROMOTIONS"),
            gmail_category="Promociones",
            authenticated_domain=None,
            list_id=None,
            unsubscribe_method="manual",
            dkim_pass=True,
            dmarc_pass=False,
            brand_hint=None,
            rubro_hint=None,
            flow_hint=Intencion.PROMOCIONAL,
            size_bytes=66300,
            fixture_tags=("ambiguous-sources-separated",),
        ),
        SyntheticMessage(
            id="ambiguous-sender-b",
            thread_id="ambiguous-b",
            received_at=_at("2026-06-05T10:00:00"),
            sender_name="Novedades",
            sender_email="grupo-b@dispatch-compartido.example",
            subject="Beneficios elegidos para vos",
            labels=("INBOX", "CATEGORY_PROMOTIONS"),
            gmail_category="Promociones",
            authenticated_domain=None,
            list_id=None,
            unsubscribe_method="manual",
            dkim_pass=True,
            dmarc_pass=False,
            brand_hint=None,
            rubro_hint=None,
            flow_hint=Intencion.PROMOCIONAL,
            size_bytes=67120,
            fixture_tags=("ambiguous-sources-separated",),
        ),
        SyntheticMessage(
            id="domotica-alert-01",
            thread_id="domotica-alert-01",
            received_at=_at("2026-08-13T02:30:00"),
            sender_name="Casa Serena",
            sender_email="alertas@casaserena.example",
            subject="El sensor de entrada perdió conexión",
            labels=("INBOX", "IMPORTANT"),
            gmail_category="Principal",
            authenticated_domain="casaserena.example",
            list_id=None,
            unsubscribe_method=None,
            dkim_pass=True,
            dmarc_pass=True,
            brand_hint="Casa Serena",
            rubro_hint=Rubro.DOMESTICOS,
            flow_hint=Intencion.NOTIFICACION,
            size_bytes=14700,
            fixture_tags=("important",),
        ),
        SyntheticMessage(
            id="community-promo-01",
            thread_id="community-promo-01",
            received_at=_at("2025-12-20T21:00:00"),
            sender_name="Ronda Común",
            sender_email="comunidad@rondacomun.example",
            subject="Volvé a conversar con la comunidad",
            labels=("INBOX", "CATEGORY_SOCIAL"),
            gmail_category="Social",
            authenticated_domain="rondacomun.example",
            list_id="actividad.rondacomun.example",
            unsubscribe_method="one_click",
            dkim_pass=True,
            dmarc_pass=True,
            brand_hint="Ronda Común",
            rubro_hint=Rubro.SOCIAL,
            flow_hint=Intencion.NOTIFICACION,
            size_bytes=44980,
        ),
    )


REQUIRED_FIXTURE_TAGS = frozenset(
    {
        "same-source-multiple-flows",
        "different-brands-same-esp",
        "brand-domain-change",
        "invoice-inside-promo",
        "security-miscategorized",
        "one-click-newsletter",
        "manual-newsletter",
        "brand-spoof-spam",
        "personal-misclassified-automated",
        "mixed-protection-thread",
        "starred",
        "important",
        "custom-label",
        "cordoba-civil-boundary",
        "partial-failure-retry",
        "obsolete-plan-label-change",
    }
)
